import { ModelFieldDescriptor } from "./ModelFieldDescriptor";
import { TileCssClass } from "./navigation/Navigatable";

export module CustomerDialogTableSettings {
    export const CustomerSelectorDialogAllColumns: string[] = [
        'customerName',
        'taxpayerNumber',
        'postalCode',
        'city',
        'thirdStateTaxId',
    ];
    export const CustomerSelectorDialogColDefs: ModelFieldDescriptor[] = [
        {
            label: 'Név',
            objectKey: 'customerName',
            colKey: 'customerName',
            defaultValue: '',
            type: 'string',
            fInputType: 'text',
            fRequired: true,
            mask: '',
            colWidth: '400px',
            textAlign: 'left',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Belföldi Adószám',
            objectKey: 'taxpayerNumber',
            colKey: 'taxpayerNumber',
            defaultValue: '',
            type: 'string',
            fInputType: 'text',
            mask: '0000000-0-00',
            colWidth: '200px',
            textAlign: 'left',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Irsz.',
            objectKey: 'postalCode',
            colKey: 'postalCode',
            defaultValue: '',
            type: 'string',
            fInputType: 'text',
            mask: '',
            colWidth: '70px',
            textAlign: 'left',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Város',
            objectKey: 'city',
            colKey: 'city',
            defaultValue: '',
            type: 'string',
            fInputType: 'text',
            fRequired: true,
            mask: '',
            colWidth: '200px',
            textAlign: 'left',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Külföldi Adószám',
            objectKey: 'thirdStateTaxId',
            colKey: 'thirdStateTaxId',
            defaultValue: '',
            type: 'string',
            fInputType: 'text',
            mask: '',
            colWidth: '135px',
            textAlign: 'left',
            navMatrixCssClass: TileCssClass,
        },
    ];
}

export module ProductGroupDialogTableSettings {
    export const ProductGroupSelectorDialogAllColumns: string[] = [
        'productGroupCode',
        'productGroupDescription'
    ];
    export const ProductGroupSelectorDialogColDefs: ModelFieldDescriptor[] = [
        {
            label: 'Kód',
            objectKey: 'productGroupCode',
            colKey: 'productGroupCode',
            defaultValue: '',
            type: 'string',
            fInputType: 'code-field',
            fRequired: true,
            mask: '',
            colWidth: '100%',
            textAlign: 'left',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Név',
            objectKey: 'productGroupDescription',
            colKey: 'productGroupDescription',
            defaultValue: '',
            type: 'string',
            fRequired: true,
            fInputType: 'text',
            mask: 'Set in sidebar form.',
            colWidth: '300px',
            textAlign: 'left',
            navMatrixCssClass: TileCssClass,
            fLast: true
        },
    ];
}

export module ProductDialogTableSettings {
    export const ProductSelectorDialogAllColumns: string[] = [
        'productCode',
        'description',
        'latestSupplyPrice',
        'exhangedUnitPrice1',
        'exhangedUnitPrice2'
    ];
    export const ProductSelectorDialogColDefs: ModelFieldDescriptor[] = [
        {
            label: 'Kód',
            objectKey: 'productCode',
            colKey: 'productCode',
            defaultValue: '',
            type: 'string',
            mask: '',
            colWidth: '26ch',
            textAlign: 'left',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Megnevezés',
            objectKey: 'description',
            colKey: 'description',
            defaultValue: '',
            type: 'string',
            mask: '',
            colWidth: '70%',
            textAlign: 'left',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Listaár',
            objectKey: 'exhangedUnitPrice1',
            colKey: 'exhangedUnitPrice1',
            defaultValue: '',
            type: 'formatted-number',
            fRequired: true,
            mask: '',
            colWidth: '130px',
            textAlign: 'right',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Egységár',
            objectKey: 'exhangedUnitPrice2',
            colKey: 'exhangedUnitPrice2',
            defaultValue: '',
            type: 'formatted-number',
            fRequired: false,
            mask: '',
            colWidth: '130px',
            textAlign: 'right',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Beszerzési ár',
            objectKey: 'latestSupplyPrice',
            colKey: 'latestSupplyPrice',
            defaultValue: '',
            type: 'formatted-number',
            fRequired: false,
            mask: '',
            colWidth: '130px',
            textAlign: 'right',
            navMatrixCssClass: TileCssClass,
        },
    ];
}

export module PendingDeliveryInvoiceSummaryDialogTableSettings {
    export const AllColumns: string[] = [
        'customerID',
        'customer',
        'fullAddress',
        'sumNetAmountDiscounted',
        'priceReview'
    ];
    export const ColDefs: ModelFieldDescriptor[] = [
        {
            label: 'Partner ID',
            objectKey: 'customerID',
            colKey: 'customerID',
            defaultValue: '',
            type: 'string',
            mask: '',
            colWidth: '120px',
            textAlign: 'left',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Partner',
            objectKey: 'customer',
            colKey: 'customer',
            defaultValue: '',
            type: 'string',
            mask: '',
            colWidth: '50%',
            textAlign: 'left',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Cím',
            objectKey: 'fullAddress',
            colKey: 'fullAddress',
            defaultValue: '',
            type: 'string',
            fRequired: true,
            mask: '',
            colWidth: '50%',
            textAlign: 'left',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Nettó',
            objectKey: 'sumNetAmountDiscounted',
            colKey: 'sumNetAmountDiscounted',
            defaultValue: '',
            type: 'formatted-number',
            fRequired: false,
            mask: '',
            colWidth: '130px',
            textAlign: 'right',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'ÁrFelv.',
            objectKey: 'priceReview',
            colKey: 'priceReview',
            defaultValue: '',
            type: 'bool',
            fRequired: false,
            mask: '',
            colWidth: '70px',
            textAlign: 'center',
            navMatrixCssClass: TileCssClass,
        },
    ];
}

export module PendingDeliveryNotesTableSettings {
    export const AllColumns: string[] = [
        'invoiceNumber',
        'relDeliveryDate',
        'productCode',
        'lineDescription',
        'quantity',
        'unitOfMeasureX',
        'unitPrice',
        'lineNetAmount',
        'priceReview'
    ];
    export const ColDefs: ModelFieldDescriptor[] = [
        {
            label: 'Szállító',
            objectKey: 'invoiceNumber',
            colKey: 'invoiceNumber',
            defaultValue: '',
            type: 'string',
            mask: '',
            colWidth: '120px',
            textAlign: 'center',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Teljesítés',
            objectKey: 'relDeliveryDate',
            colKey: 'relDeliveryDate',
            defaultValue: '',
            type: 'onlyDate',
            mask: '',
            colWidth: '105px',
            textAlign: 'left',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Termékkód',
            objectKey: 'productCode',
            colKey: 'productCode',
            defaultValue: '',
            type: 'string',
            fRequired: true,
            mask: '',
            colWidth: '30%',
            textAlign: 'center',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Terméknév',
            objectKey: 'lineDescription',
            colKey: 'lineDescription',
            defaultValue: '',
            type: 'string',
            fRequired: false,
            mask: '',
            colWidth: '70%',
            textAlign: 'left',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Menny.',
            objectKey: 'quantity',
            colKey: 'quantity',
            defaultValue: '',
            type: 'formatted-number',
            fRequired: false,
            mask: '',
            colWidth: '70px',
            textAlign: 'right',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Me.E.',
            objectKey: 'unitOfMeasureX',
            colKey: 'unitOfMeasureX',
            defaultValue: '',
            type: 'string',
            fRequired: false,
            mask: '',
            colWidth: '70px',
            textAlign: 'left',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Száll. Ár.',
            objectKey: 'unitPrice',
            colKey: 'unitPrice',
            defaultValue: '',
            type: 'formatted-number',
            fRequired: false,
            mask: '',
            colWidth: '100px',
            textAlign: 'right',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Nettó',
            objectKey: 'lineNetAmount',
            colKey: 'lineNetAmount',
            defaultValue: '',
            type: 'formatted-number',
            fRequired: false,
            mask: '',
            colWidth: '100px',
            textAlign: 'right',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'ÁrFelv.',
            objectKey: 'priceReview',
            colKey: 'priceReview',
            defaultValue: '',
            type: 'bool',
            fRequired: false,
            mask: '',
            colWidth: '70px',
            textAlign: 'center',
            navMatrixCssClass: TileCssClass,
        },
    ];
}

export module PendingDeliveryNotesByInvoiceNumberTableSettings {
    export const AllColumns: string[] = [
        'invoiceNumber',
        'relDeliveryDate',
        'workNumber',
    ];
    export const ColDefs: ModelFieldDescriptor[] = [
        {
            label: 'Szállító',
            objectKey: 'invoiceNumber',
            colKey: 'invoiceNumber',
            defaultValue: '',
            type: 'string',
            mask: '',
            colWidth: '33%',
            textAlign: 'center',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Teljesítés',
            objectKey: 'relDeliveryDate',
            colKey: 'relDeliveryDate',
            defaultValue: '',
            type: 'onlyDate',
            mask: '',
            colWidth: '33%',
            textAlign: 'left',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Munkaszám',
            objectKey: 'workNumber',
            colKey: 'workNumber',
            defaultValue: '',
            type: 'string',
            fRequired: true,
            mask: '',
            colWidth: '33%',
            textAlign: 'center',
            navMatrixCssClass: TileCssClass,
        },
    ];
}

export module GetPendingDeliveryNotesDialogTableSettings {
    export const AllColumns: string[] = [
        'invoiceNumber',
        'invoiceDeliveryDate',
        'customer',
        'fullAddress',
        'sumNetAmountDiscounted',
        'priceReview',
    ];
    export const ColDefs: ModelFieldDescriptor[] = [
        {
            label: 'Száll.szám',
            objectKey: 'invoiceNumber',
            colKey: 'invoiceNumber',
            defaultValue: '',
            type: 'string',
            mask: '',
            colWidth: '120px',
            textAlign: 'center',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Telj.',
            objectKey: 'invoiceDeliveryDate',
            colKey: 'invoiceDeliveryDate',
            defaultValue: '',
            type: 'onlyDate',
            mask: '',
            colWidth: '120px',
            textAlign: 'left',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Partner',
            objectKey: 'customer',
            colKey: 'customer',
            defaultValue: '',
            type: 'string',
            fRequired: true,
            mask: '',
            colWidth: '33%',
            textAlign: 'center',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Cím',
            objectKey: 'fullAddress',
            colKey: 'fullAddress',
            defaultValue: '',
            type: 'string',
            fRequired: true,
            mask: '',
            colWidth: '33%',
            textAlign: 'center',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Nettó',
            objectKey: 'sumNetAmountDiscounted',
            colKey: 'sumNetAmountDiscounted',
            defaultValue: '',
            type: 'formatted-number',
            fRequired: true,
            mask: '',
            colWidth: '150px',
            textAlign: 'center',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Ár felülv.',
            objectKey: 'priceReview',
            colKey: 'priceReview',
            defaultValue: '',
            type: 'bool',
            fRequired: true,
            mask: '',
            colWidth: '85px',
            textAlign: 'center',
            navMatrixCssClass: TileCssClass,
        },
    ];
}

export module InvoiceItemsDialogTableSettings {
    export const AllColumns: string[] = [
        'productCode',
        'lineDescription',
        'quantity',
        'unitOfMeasureX',
        'lineNetAmount',
    ];
    export const ColDefs: ModelFieldDescriptor[] = [
        {
            label: 'Termékkód',
            objectKey: 'productCode',
            colKey: 'productCode',
            defaultValue: '',
            type: 'string',
            mask: '',
            colWidth: '30%',
            textAlign: 'center',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Terméknév',
            objectKey: 'lineDescription',
            colKey: 'lineDescription',
            defaultValue: '',
            type: 'string',
            mask: '',
            colWidth: '70%',
            textAlign: 'left',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Menny.',
            objectKey: 'quantity',
            colKey: 'quantity',
            defaultValue: '',
            type: 'formatted-number',
            fRequired: true,
            mask: '',
            colWidth: '70px',
            textAlign: 'right',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Me.E.',
            objectKey: 'unitOfMeasureX',
            colKey: 'unitOfMeasureX',
            defaultValue: '',
            type: 'string',
            fRequired: true,
            mask: '',
            colWidth: '70px',
            textAlign: 'left',
            navMatrixCssClass: TileCssClass,
        },
        {
            label: 'Nettó',
            objectKey: 'lineNetAmount',
            colKey: 'lineNetAmount',
            defaultValue: '',
            type: 'formatted-number',
            fRequired: true,
            mask: '',
            colWidth: '150px',
            textAlign: 'center',
            navMatrixCssClass: TileCssClass,
        },
    ];
}
