import { InvoiceLine } from "./InvoiceLine";

export interface Invoice {
    id: number,
    incoming: boolean,
    warehouseID: number,
    warehouse: string,
    invoiceNumber: string,
    invoiceIssueDate: string,
    invoiceDeliveryDate: string,
    paymentDate: string,
    supplierID: number,
    supplierName: string,
    SupplierBankAccountNumber?: any,
    supplierTaxpayerNumber: string,
    supplierCountryCode: string,
    supplierPostalCode: string,
    supplierCity: string,
    supplierAdditionalAddressDetail: string,
    supplierComment: string,
    supplierThirdStateTaxId?: string,
    customerID: number,
    customerName: string,
    customerBankAccountNumber: string,
    customerTaxpayerNumber: string,
    customerThirdStateTaxId: string,
    customerCountryCode: string,
    customerPostalCode: string,
    customerCity: string,
    customerAdditionalAddressDetail: string,
    customerInvoiceNumber: string,
    customerVatStatus: string,
    CustomerComment?: any,
    paymentMethod: string,
    paymentMethodX: string,
    notice: string,
    invoiceNetAmount: number,
    invoiceVatAmount: number,
    invoiceGrossAmount: number,
    invoiceLines: InvoiceLine[],
    invoiceDiscountPercent: number,
}