import { InvoiceLine } from "out/bbx-ui-win32-x64/resources/app/src/app/modules/invoice/models/InvoiceLine"

export interface Invoice {
    "id": number,
    "warehouseID": number,
    "warehouse": string, // "001-Raktár"
    "invoiceNumber": string,
    "invoiceIssueDate": string,
    "invoiceDeliveryDate": string,
    "paymentDate": string,
    "supplierID": number,
    "supplierName": string,
    "SupplierBankAccountNumber"?: any,
    "supplierTaxpayerNumber": string,
    "supplierCountryCode": string,
    "supplierPostalCode": string,
    "supplierCity": string,
    "supplierAdditionalAddressDetail": string,
    "supplierComment": string,
    "customerID": number,
    "customerName": string,
    "customerBankAccountNumber": string,
    "customerTaxpayerNumber": string,
    "customerCountryCode": string,
    "customerPostalCode": string,
    "customerCity": string,
    "customerAdditionalAddressDetail": string,
    "CustomerComment"?: any,
    "paymentMethod": string,
    "paymentMethodX": string,
    "notice": string,
    "invoiceNetAmount": number,
    "invoiceVatAmount": number,
    "InvoiceLines": InvoiceLine[]
}