name: Build and deploy bbxFE to DEV environment


on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install

      #- name: Run tests
      #  run: npm run test:headless

      - name: Build
        run: npm run build-prod
        #run: ng build --prod --base-href
