name: Build and deploy bbxFE to DEV environment

env:
  STORAGE_NAME: bbx   # set this to your storage's name
  AZURE_STORAGE_KEY: W6pStudoWs5SVxEJCwZeDILx5Kv1gYQ0Rut5P+ggnOpFSGI7CH5d4gjR2wwS60ey4ULYC+EgKkznMGsoxlYIGw==
  CONNECTION_STRING: DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=bbx;AccountKey=W6pStudoWs5SVxEJCwZeDILx5Kv1gYQ0Rut5P+ggnOpFSGI7CH5d4gjR2wwS60ey4ULYC+EgKkznMGsoxlYIGw==;BlobEndpoint=https://bbx.blob.core.windows.net/;FileEndpoint=https://bbx.file.core.windows.net/;QueueEndpoint=https://bbx.queue.core.windows.net/;TableEndpoint=https://bbx.table.core.windows.net/
  
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install

      #- name: Run tests
      #  run: npm run test:headless

      - name: Build
        run: npm run build-prod
        #run: ng build --prod --base-href
        
      - name: Azure checkout
        uses: actions/checkout@v3
        
      - name: Azure login
        uses: azure/login@v1
        with:
           creds: ${{ secrets.BBXFE_DEV_PUBLISH_PROFILE }}
           
      - name: Upload to Azure Blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
             az storage blob upload-batch --connection-string env.CONNECTION_STRING -d '$web' -s .
