name: Build and deploy bbxFE to DEV environment


on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install

      #- name: Run tests
      #  run: npm run test:headless

      - name: Build
        run: npm run build-prod
        #run: ng build --prod --base-href
        
      - name: Azure checkout
        uses: actions/checkout@v3
        
      - name: Azure login
        uses: azure/login@v1
        with:
           creds: ${{ secrets.BBXFE_DEV_PUBLISH_PROFILE }}
           
      - name: Upload to Azure Blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
             az storage blob upload-batch --account-name bbx --auth-mode key -d '$web' -s .
