# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy bbxFE to DEV environment

env:
  STORAGE_NAME: bbx # set this to your storage's name
  AZURE_STORAGE_KEY: W6pStudoWs5SVxEJCwZeDILx5Kv1gYQ0Rut5P+ggnOpFSGI7CH5d4gjR2wwS60ey4ULYC+EgKkznMGsoxlYIGw==
  CONNECTION_STRING: DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=bbx;AccountKey=W6pStudoWs5SVxEJCwZeDILx5Kv1gYQ0Rut5P+ggnOpFSGI7CH5d4gjR2wwS60ey4ULYC+EgKkznMGsoxlYIGw==;
  PROJECT_NAME: bbx-ui
  SHA_SHORT_COMMIT_NUMBER: 0
  PACKAGE_VERSION: 0

on:
  pull_request: 
    branches: [ develop ]
    types: [ closed ]
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    name: Build bbxUI Angular project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v3

      - name: Get Short SHA commit number
        shell: bash
        run: |
          echo "SHA_SHORT_COMMIT_NUMBER=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install
        
#      - name: Versioning
#        run: npm version minor && npm publish && npm version patch 
#        #&& git push --tags && git push origin master

      - name: Print Package Version
        run: |
          echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> "$GITHUB_ENV"

      - name: package.json info
        id: info
        uses: jaywcjlove/github-action-package@main
        with:
          version: ${{ env.PACKAGE_VERSION }} - ${{ env.SHA_SHORT_COMMIT_NUMBER }}
      - run: echo "${{ env.PACKAGE_VERSION }} - ${{ env.SHA_SHORT_COMMIT_NUMBER }}"

     # - name: Early exit
     #   run: |
     #     gh run cancel ${{ github.run_id }}
     #     gh run watch ${{ github.run_id }}
     #   env:
     #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          
      - name: Build
        run: npm run build-prod
        #run: ng build --prod --base-href   

      #- name: Run tests
      #  run: npm run test -- --configuration production
      #  env:
      #      CI: true
        # npm run test :headless
        
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist

  deploy:
    if: ${{ github.event.pull_request.merged }}
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: Development
      url: https://bbx.z1.web.core.windows.net/index.html
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.BBXFE_DEV_PUBLISH_PROFILE }}

      - name: Delete the content of the blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob delete-batch --account-name $STORAGE_NAME --auth-mode key --source '$web' --pattern '*'
            
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: deploy_dist

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name $STORAGE_NAME --auth-mode key -d '$web' -s ./deploy_dist/$PROJECT_NAME --overwrite

      - name: Azure Logout
        run: |
          az logout
        if: always()

      #- name: Azure checkout
      #  uses: actions/checkout@v3
